services:
  rustapp:
    container_name: rustapp
    image: nkuros/rustapp:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:admin@db:5432/postgres
    ports:
      - '9090:9090'
    depends_on:
      - db

  db:
    container_name: db
    image: 'postgres:16'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}